#!/bin/bash -l

#SBATCH -n 4
#SBATCH -N 4

mpirun apm 0 dna/big_chr.fa AGAA GTAGGGTTGCACGAGACAGAACTAGCTTAGGCACTATTTGTCCAAATACA CTGTATTGGTGCGCGTTGACCAGA AGAA TGTA ACCAGT # 33 secondes en séquentiel
# 10 secondes en Cas 1
# ./apm 0 dna/medium_chr.fa AGAA AGATCCCCGGACCTGTCCTCCTGGTT CTGTATTGGTGCGCGTTGACCAGA AGAA TGTA ACCAGT
