#!/bin/bash -l

#SBATCH -n 8
#SBATCH -N 8

mpirun apm 0 dna/medium_chr.fa AGAA ACCAGTGTGTACAC AGAA TGTA ACCAGT AGGT CGTAC CGHATC ACGT AGAA ACCAGTGTGTACAC AGAA TGTA ACCAGT AGGT CGTAC CGHATC ACGT AGAA ACCAGTGTGTACAC AGAA TGTA ACCAGT AGGT CGTAC CGHATC ACGT AGAA ACCAGTGTGTACAC AGAA TGTA ACCAGT AGGT CGTAC CGHATC ACGT AGAA ACCAGTGTGTACAC AGAA TGTA ACCAGT AGGT CGTAC CGHATC ACGT AGAA ACCAGTGTGTACAC AGAA TGTA ACCAGT AGGT CGTAC CGHATC ACGT AGAA ACCAGTGTGTACAC AGAA TGTA ACCAGT AGGT CGTAC CGHATC ACGT AGAA ACCAGTGTGTACAC AGAA TGTA ACCAGT AGGT CGTAC CGHATC ACGT AGAA ACCAGTGTGTACAC AGAA TGTA ACCAGT AGGT CGTAC CGHATC ACGT AGAA ACCAGTGTGTACAC AGAA TGTA ACCAGT AGGT CGTAC CGHATC ACGT AGAA ACCAGTGTGTACAC AGAA TGTA ACCAGT AGGT CGTAC CGHATC ACGT AGAA ACCAGTGTGTACAC AGAA TGTA ACCAGT AGGT CGTAC CGHATC ACGTAGAA ACCAGTGTGTACAC AGAA TGTA ACCAGT AGGT CGTAC CGHATC ACGT AGAA ACCAGTGTGTACAC AGAA TGTA ACCAGT AGGT CGTAC CGHATC ACGT AGAA ACCAGTGTGTACAC AGAA TGTA ACCAGT AGGT CGTAC CGHATC ACGT AGAA ACCAGTGTGTACAC AGAA TGTA ACCAGT AGGT CGTAC CGHATC ACGT AGAA ACCAGTGTGTACAC AGAA TGTA ACCAGT AGGT CGTAC CGHATC ACGT AGAA ACCAGTGTGTACAC AGAA TGTA ACCAGT AGGT CGTAC CGHATC ACGTAGAA ACCAGTGTGTACAC AGAA TGTA ACCAGT AGGT CGTAC CGHATC ACGT AGAA ACCAGTGTGTACAC AGAA TGTA ACCAGT AGGT CGTAC CGHATC ACGT AGAA ACCAGTGTGTACAC AGAA TGTA ACCAGT AGGT CGTAC CGHATC ACGT AGAA ACCAGTGTGTACAC AGAA TGTA ACCAGT AGGT CGTAC CGHATC ACGT AGAA ACCAGTGTGTACAC AGAA TGTA ACCAGT AGGT CGTAC CGHATC ACGT AGAA ACCAGTGTGTACAC AGAA TGTA ACCAGT AGGT CGTAC CGHATC ACGT
# Prend 0,08 s
# Prend 0,18 s en séquentiel


# Util à partir de 100 paterns
